name = "TFC 2023 Server"
author = "Treeway7"
version = "1.1.0"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca59f18053551aed3018d150720da60222858db0abb2dd7aecd5eff31bbf4019"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
